### ISSUE TITLE
Starting composer-playground to connect to a network running on Starter Plan instance results in errors

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#32]
Installed `composer-playground@0.18.1` locally on my laptop. After successfully deploying the car-auction business network identified by `Matterhorn Network - 4a` to the IBM Starter Plan instance and testing using the `composer-rest-server@0.18.1`, I started `composer-playground` from the same directory which contains the `connection-profile.json` for `org1` -- just like I did when testing with `composer-rest-server`. `composer-playground` starts a new browser tab pointing to `localhost:8080` and connects to the IBM Starter Plan instance as it shows the `Connection:  Matterhorn Network - 4a` at the top of the tab. When I try to connect to the carauction-network, I see the following errors in the terminal window where I started `composer-playground`:

```
HLFConnectionManager    :fabric-client()          [Client.js]: setUserContext - resolved user 
HLFConnection           :login()                  User loaded from persistence and has already enrolled 
HLFConnection           :login()                  Creating new security context 
HLFConnection           :_connectToEventHubs()    > 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getOrganization - name org1 
HLFConnectionManager    :fabric-client()          [Organization.js]: Organization.const  
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getPeer - name org1-peer1 
HLFConnectionManager    :fabric-client()          [Peer.js]: Peer.const - url: grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31002 timeout: 45000 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getEventHub - name org1-peer1 
HLFConnectionManager    :fabric-client()          [EventHub.js]: const  
HLFConnectionManager    :fabric-client()          [EventHub.js]: setPeerAddr -  grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31003 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _disconnect - start -- called due to:: EventHub has been shutdown due to new Peer address assignment 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - start 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - blockOnErrors 0 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - transactionOnErrors 0 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - chaincodeRegistrants 0 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getCertificateAuthority - name org1-ca 
HLFConnectionManager    :fabric-client()          [CertificateAuthority.js]: CertificateAuthority.const  
HLFConnectionManager    :fabric-client()          [CertificateAuthority.js]: Organization.const  
HLFConnectionManager    :fabric-client()          [EventHub.js]: connect - start 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _connect - start - Mon Apr 23 2018 16:04:06 GMT-0700 (PDT) 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _connect - start stream: 1 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _connect - options {"grpc.http2.min_time_between_pings_ms":300000,"grpc.keepalive_timeout_ms":180000,"grpc.http2.keepalive_timeout":180,"grpc.keepalive_time_ms":360000,"grpc.http2.keepalive_time":360,"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1} 
HLFConnectionManager    :fabric-client()          [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: 82d48ee6b201487d2a25da22bd36ee18cd5b03c1fadb7112935c5c0100410ca5>,
  s: <BN: 9cbf7f77fdb5481d05c2f348a043467fa8852fbf50f9c42c7d1531cdf152e6a>,
  recoveryParam: 0 } 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _connect - end stream: 1 
HLFConnection           :_connectToEventHubs()    registerChaincodeEvent carauction-network, composer
HLFConnectionManager    :fabric-client()          [EventHub.js]: registerChaincodeEvent - start 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _checkConnection - start throw_error true, force_reconnect false 
HLFConnectionManager    :fabric-client()          [Remote.js]: getUrl::grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31003 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _checkConnection - this hub grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31003 is connected or trying to connect with stream channel state 0 
HLFConnection           :_connectToEventHubs()    register exit listener for connector 
HLFConnection           :_connectToEventHubs()    < 
HLFConnection           :login()                  < [object Object]
ConnectorServer         :connectionLogin()        < 8779a2c3-a971-40db-8890-4984433a1102
ConnectorServer         :connectionPing()         > 399a5f9b-d1ba-4cba-8c6f-2d16be53f4ae, 8779a2c3-a971-40db-8890-4984433a1102
HLFConnection           :ping()                   > [object Object]
HLFConnection           :_checkRuntimeVersions()  > [object Object]
HLFConnection           :queryChainCode()         > [object Object], ping, []
HLFConnectionManager    :fabric-client()          [Client.js]: newTransactionID - no admin parameter, returning non admin TransactionID 
HLFConnectionManager    :fabric-client()          [Client.js]: _getSigningIdentity - admin parameter is boolean :false 
HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id 1d48f687ea3a5d61540ac90be97c6fba35e4d719fa0c17c3f008cb5a99b5cb50 
HLFConnectionManager    :fabric-client()          [Channel.js]: getPeers - list size: 1. 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getOrganization - name org1 
HLFConnectionManager    :fabric-client()          [Organization.js]: Organization.const  
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getPeer - name org1-peer1 
HLFConnectionManager    :fabric-client()          [Peer.js]: Peer.const - url: grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31002 timeout: 45000 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getEventHub - name org1-peer1 
HLFConnectionManager    :fabric-client()          [EventHub.js]: const  
HLFConnectionManager    :fabric-client()          [EventHub.js]: setPeerAddr -  grpcs://n32d85dd29e5a48f3835dea9b31a66360-org1-peer1.us8.blockchain.ibm.com:31003 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _disconnect - start -- called due to:: EventHub has been shutdown due to new Peer address assignment 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - start 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - blockOnErrors 0 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - transactionOnErrors 0 
HLFConnectionManager    :fabric-client()          [EventHub.js]: _closeAllCallbacks - chaincodeRegistrants 0 
HLFConnectionManager    :fabric-client()          [NetworkConfig101.js]: getCertificateAuthority - name org1-ca 
HLFConnectionManager    :fabric-client()          [CertificateAuthority.js]: CertificateAuthority.const  
HLFConnectionManager    :fabric-client()          [CertificateAuthority.js]: Organization.const  
HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincode - start 
HLFConnectionManager    :fabric-client()          [Client.js]: getTargetPeers - start 
HLFConnectionManager    :fabric-client()          [Client.js]: _getSigningIdentity - admin parameter is undefined :undefined 
HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id 0e2754e85f6dedf0fe00e8cfb0e770216a41489e79f45d6a71230cdd16f83ba8 
HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - start 
HLFConnectionManager    :fabric-client()          [Client.js]: getTargetPeers - start 
HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding function arg:ping 
HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - not adding the argument :: argbytes 
HLFConnectionManager    :fabric-client()          [client-utils.js]: buildChannelHeader - type 3 channel_id defaultchannel tx_id NaN epoch % chaincode_id null carauction-network 
HLFConnectionManager    :fabric-client()          [client-utils.js]: buildProposal - not adding a transientMap 
HLFConnectionManager    :fabric-client()          [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: 75317a869ad9601a957ccb0bcdc8ffb678affffa4a49e6051cf83443f3e3cc6e>,
  s: <BN: 71ba500b8075cf8d3f29820f98310457fec8e31c04bb615dfe98a7fae7fc233e>,
  recoveryParam: 0 } 
HLFConnectionManager    :fabric-client()          [Peer.js]: Peer.sendProposal - Start 
HLFConnectionManager    :fabric-client()          [EventHub.js]: on.data - event stream:1 _current_stream:1 
HLFConnectionManager    :fabric-client()          [EventHub.js]: on.data - grpc stream state :2 
HLFConnectionManager    :fabric-client()          [EventHub.js]: on.data - register event received 
HLFConnectionManager    :fabric-client()          [Peer.js]: sendProposal - timed out after:45000 
HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/Users/sanjaysaxena/.nvm/versions/node/v8.9.1/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) 
HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT 
HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincode - results received 
HLFConnection           :queryChainCode()         Received 1 payloads(s) from querying the composer runtime chaincode [{}]
HLFConnection           :queryChainCode()         Error: Error trying to query business network. Error: REQUEST_TIMEOUT 
HLFConnection           :ping()                   Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT 
ConnectorServer         :Error: Error trying to p undefined 
```

**Comment by lesleyannjordan** [comment]
@sanjay-saxena please can you clarify what documentation you have been following?  Is this still an issue? Starter plan has moved on to fabric 1.1 and correspondingly composer 0.19.x

**Comment by sanjay-saxena** [comment]
You are right that the Starter Plan has moved to HF 1.1. And, HC 0.19.X is the compatible version.

Here is the [tutorial](https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/index.html) that I used to deploy the network to the Starter Plan instance. It is based on HC 0.19.5. You can try to deploy a network using those steps and then try to connect to the network by   using the exact same version of `composer-playground`.

**Comment by lesleyannjordan** [comment]
Hi @sanjay-saxena please can you detail what IBP documentation changes you see suggesting requires updating, this is not clear from the description.

Please note it is not a recommended use case to use Plaground for interacting with an IBP instance such as Starter Plan or Enterprise.

**Comment by sanjay-saxena** [comment]
I think it would be pretty common for teams to have separate IBP instances for -- `Development`, `Stage`, and `Production` -- environments. In such a scenario, it would make sense for a dev team to deploy a business network to their `Development` IBP instance and test it out by connecting to it using `composer-playground` that is running locally. Similarly, the QA team can test using the IBP instance in the `Stage` environment.

I am not sure if there is any documentation that currently exists which describes this usage and needs to updated/fixed. Perhaps, this ticket can be used to create new documentation that would help teams of developers in their `run/test/debug` cycles in various environments.

**Comment by wjzhengsh** [comment]
Close this issue for now as we provide limited support to Composer now.
